"""Markdown and JSON report helpers."""

from app.models.schemas import ResonanceReport


def to_markdown(report: ResonanceReport) -> str:
    """Render a ResonanceReport as a professional Markdown document."""
    d = report.diagnosis
    a = report.architecture
    g = report.generated_code
    c = report.critique

    lines: list[str] = []
    lines.append("# ResonanceForge Assessment Report")
    lines.append("")
    lines.append("## Question")
    lines.append("")
    lines.append(report.user_question)
    lines.append("")

    lines.append("## Diagnosis (ACCESS / ADAPT / ADOPT)")
    lines.append("")
    lines.append(f"**Overall readiness:** {d.overall_readiness}")
    lines.append("")
    lines.append(f"| Dimension | Score | Reason |")
    lines.append(f"|-----------|------:|--------|")
    lines.append(f"| ACCESS | {d.access.score}/10 | {d.access.reason} |")
    lines.append(f"| ADAPT | {d.adapt.score}/10 | {d.adapt.reason} |")
    lines.append(f"| ADOPT | {d.adopt.score}/10 | {d.adopt.reason} |")
    lines.append("")
    lines.append("### Top gaps")
    lines.append("")
    for gap in d.top_gaps:
        lines.append(f"- {gap}")
    lines.append("")
    lines.append("### Summary")
    lines.append("")
    lines.append(d.summary)
    lines.append("")

    lines.append("## Architecture")
    lines.append("")
    lines.append(f"**Estimated complexity:** {a.estimated_complexity}")
    lines.append("")
    lines.append("### Recommended agents")
    lines.append("")
    for agent in a.recommended_agents:
        lines.append(f"- **{agent.name}** — {agent.responsibility}")
    lines.append("")
    lines.append("### High-level flow")
    lines.append("")
    for i, step in enumerate(a.high_level_flow, 1):
        lines.append(f"{i}. {step}")
    lines.append("")
    lines.append("### Rationale")
    lines.append("")
    lines.append(a.rationale)
    lines.append("")

    lines.append("## Generated LangGraph Code")
    lines.append("")
    lines.append(g.explanation)
    lines.append("")
    lines.append("```python")
    lines.append(g.code.rstrip())
    lines.append("```")
    lines.append("")

    lines.append("## Critique")
    lines.append("")
    lines.append(f"**Final verdict:** {c.final_verdict}")
    lines.append("")
    lines.append("### Strengths")
    lines.append("")
    for item in c.strengths:
        lines.append(f"- {item}")
    lines.append("")
    lines.append("### Weaknesses")
    lines.append("")
    for item in c.weaknesses:
        lines.append(f"- {item}")
    lines.append("")
    lines.append("### Risks")
    lines.append("")
    for item in c.risks:
        lines.append(f"- {item}")
    lines.append("")
    lines.append("### Recommendations")
    lines.append("")
    for item in c.recommendations:
        lines.append(f"- {item}")
    lines.append("")
    lines.append("---")
    lines.append("*Generated by ResonanceForge v1*")
    lines.append("")

    return "\n".join(lines)
